apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: nodejs-nodeclass
spec:
  amiFamily: AL2023

  amiSelectorTerms:
    - alias: al2023@latest

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-cluster

  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-cluster

  role: karpenter-node-eks-cluster-role
